# Generated by Django 6.0 on 2026-08-14 09:08

import care_pinelabs.utils.encrypted_field
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emr', '0080_alter_activitydefinition_category_and_more'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinelabsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('default_payment_flow', models.CharField(blank=True, choices=[('pinelabs', 'Pinelabs'), ('native', 'Native')], max_length=255, null=True)),
                ('allow_advance_payment', models.BooleanField(default=True)),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('pinelabs_merchant_id', models.CharField(max_length=255)),
                ('pinelabs_security_token', care_pinelabs.utils.encrypted_field.EncryptedCharField()),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinelabsPaymentMethodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('care_method', models.CharField(max_length=255)),
                ('pinelabs_method', models.CharField(choices=[('1', 'Card'), ('8', 'PhonePe'), ('10', 'UPI Sale'), ('11', 'UPI Bharat QR'), ('21', 'Amazon Pay')], max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_mappings', to='care_pinelabs.pinelabsconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PinelabsPosTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_pinelabs.pinelabsconfig')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emr.device')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinelabsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_number', models.CharField(db_index=True, help_text='Unique transaction number (format: A{account_id}-{invoice}-{seq})', max_length=100, unique=True)),
                ('plutus_transaction_reference_id', models.CharField(blank=True, db_index=True, help_text='PTRID returned by Pine Labs', max_length=100, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='started', help_text='Current transaction status', max_length=20)),
                ('payment_mode', models.CharField(help_text='Payment mode: 1=Card, 10=UPI, 11=Bharat QR', max_length=10)),
                ('account', models.ForeignKey(help_text='Account being charged', on_delete=django.db.models.deletion.PROTECT, related_name='terminal_transactions', to='emr.account')),
                ('invoice', models.ForeignKey(blank=True, help_text='Optional invoice being paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_transactions', to='emr.invoice')),
                ('payment_reconciliation', models.OneToOneField(blank=True, help_text='Linked payment reconciliation record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_transaction', to='emr.paymentreconciliation')),
                ('terminal', models.ForeignKey(help_text='Terminal processing this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='care_pinelabs.pinelabsposterminal')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='pinelabsconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('facility',), name='unique_active_facility_per_pinelabs_config'),
        ),
        migrations.AddConstraint(
            model_name='pinelabspaymentmethodmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('config', 'pinelabs_method'), name='unique_care_method_per_config'),
        ),
        migrations.AddConstraint(
            model_name='pinelabspaymentmethodmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_default', True)), fields=('config',), name='unique_default_payment_method_per_config'),
        ),
        migrations.AddConstraint(
            model_name='pinelabsposterminal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('device',), name='unique_active_device_per_pos_terminal'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['terminal', 'status'], name='care_pinela_termina_9cfaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['account', 'status'], name='care_pinela_account_4d4c94_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['invoice', 'status'], name='care_pinela_invoice_998e23_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['status', 'created_date'], name='care_pinela_status_de732e_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['payment_reconciliation'], name='care_pinela_payment_3890ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['plutus_transaction_reference_id'], name='care_pinela_plutus__d374a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'in_progress'])), fields=('terminal',), name='unique_active_transaction_per_terminal', violation_error_message='Terminal already has an active transaction'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), ('status__in', ['started', 'in_progress'])), fields=('invoice',), name='unique_active_payment_per_invoice', violation_error_message='Invoice already has an active payment in progress'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', True), ('status__in', ['started', 'in_progress'])), fields=('account',), name='unique_active_payment_per_account', violation_error_message='Account already has an active payment in progress'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(fields=('transaction_number',), name='unique_transaction_number', violation_error_message='Transaction number already exists'),
        ),
    ]
