# Generated by Django 6.0 on 2026-08-06 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0001_initial'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinelabsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_number', models.CharField(db_index=True, help_text='Unique transaction number (format: A{account_id}-{invoice}-{seq})', max_length=100, unique=True)),
                ('plutus_transaction_reference_id', models.CharField(blank=True, db_index=True, help_text='PTRID returned by Pine Labs', max_length=100, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='started', help_text='Current transaction status', max_length=20)),
                ('payment_mode', models.CharField(help_text='Payment mode: 1=Card, 10=UPI, 11=Bharat QR', max_length=10)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_termina_dff131_idx',
        ),
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_account_1df734_idx',
        ),
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_invoice_bbc122_idx',
        ),
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_status_dde0c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_payment_221c40_idx',
        ),
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_plutus__0df643_idx',
        ),
        migrations.RemoveConstraint(
            model_name='pinelabsterminaltransaction',
            name='unique_active_transaction_per_terminal',
        ),
        migrations.RemoveConstraint(
            model_name='pinelabsterminaltransaction',
            name='unique_active_payment_per_invoice',
        ),
        migrations.RemoveConstraint(
            model_name='pinelabsterminaltransaction',
            name='unique_active_payment_per_account',
        ),
        migrations.RemoveConstraint(
            model_name='pinelabsterminaltransaction',
            name='unique_transaction_number',
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='account',
            field=models.ForeignKey(help_text='Account being charged', on_delete=django.db.models.deletion.PROTECT, related_name='terminal_transactions', to='emr.account'),
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Optional invoice being paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_transactions', to='emr.invoice'),
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='payment_reconciliation',
            field=models.OneToOneField(blank=True, help_text='Linked payment reconciliation record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_transaction', to='emr.paymentreconciliation'),
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='terminal',
            field=models.ForeignKey(help_text='Terminal processing this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='care_pinelabs.pinelabsposterminal'),
        ),
        migrations.RemoveField(
            model_name='pinelabsterminaltransaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='pinelabsterminaltransaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='pinelabsterminaltransaction',
            name='payment_reconciliation',
        ),
        migrations.RemoveField(
            model_name='pinelabsterminaltransaction',
            name='terminal',
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['terminal', 'status'], name='care_pinela_termina_9cfaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['account', 'status'], name='care_pinela_account_4d4c94_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['invoice', 'status'], name='care_pinela_invoice_998e23_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['status', 'created_date'], name='care_pinela_status_de732e_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['payment_reconciliation'], name='care_pinela_payment_3890ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['plutus_transaction_reference_id'], name='care_pinela_plutus__d374a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'in_progress'])), fields=('terminal',), name='unique_active_transaction_per_terminal', violation_error_message='Terminal already has an active transaction'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), ('status__in', ['started', 'in_progress'])), fields=('invoice',), name='unique_active_payment_per_invoice', violation_error_message='Invoice already has an active payment in progress'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', True), ('status__in', ['started', 'in_progress'])), fields=('account',), name='unique_active_payment_per_account', violation_error_message='Account already has an active payment in progress'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(fields=('transaction_number',), name='unique_transaction_number', violation_error_message='Transaction number already exists'),
        ),
        migrations.DeleteModel(
            name='PinelabsTerminalTransaction',
        ),
    ]
