# Generated by Django 6.0 on 2026-08-06 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


def check_table_exists(schema_editor, table_name):
    """Check if a table exists before trying to modify it."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = 'public'
                AND table_name = %s
            );
        """, [table_name])
        return cursor.fetchone()[0]


def ensure_pos_terminal_table_exists(apps, schema_editor):
    """Ensure PinelabsPosTerminal table exists before creating foreign keys to it."""
    if check_table_exists(schema_editor, 'care_pinelabs_pinelabsposterminal'):
        return  # Table already exists

    # Table doesn't exist, create it from the model state
    # This shouldn't normally happen, but protects against migration optimization issues
    PinelabsPosTerminal = apps.get_model('care_pinelabs', 'PinelabsPosTerminal')
    schema_editor.create_model(PinelabsPosTerminal)


def remove_old_indexes_and_constraints(apps, schema_editor):
    """Remove indexes and constraints from old table if it exists."""
    if not check_table_exists(schema_editor, 'pinelabs_terminal_transaction'):
        return  # Skip if table doesn't exist (fresh deployment)

    # Drop indexes
    with schema_editor.connection.cursor() as cursor:
        indexes = [
            'pinelabs_te_termina_dff131_idx',
            'pinelabs_te_account_1df734_idx',
            'pinelabs_te_invoice_bbc122_idx',
            'pinelabs_te_status_dde0c4_idx',
            'pinelabs_te_payment_221c40_idx',
            'pinelabs_te_plutus__0df643_idx',
        ]
        for index_name in indexes:
            cursor.execute(f"DROP INDEX IF EXISTS {index_name};")

        # Drop constraints
        constraints = [
            'unique_active_transaction_per_terminal',
            'unique_active_payment_per_invoice',
            'unique_active_payment_per_account',
            'unique_transaction_number',
        ]
        for constraint_name in constraints:
            cursor.execute(f"ALTER TABLE pinelabs_terminal_transaction DROP CONSTRAINT IF EXISTS {constraint_name};")


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0001_initial'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        # Ensure PinelabsPosTerminal table exists before creating FK to it
        migrations.RunPython(
            ensure_pos_terminal_table_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='PinelabsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('transaction_number', models.CharField(db_index=True, help_text='Unique transaction number (format: A{account_id}-{invoice}-{seq})', max_length=100, unique=True)),
                ('plutus_transaction_reference_id', models.CharField(blank=True, db_index=True, help_text='PTRID returned by Pine Labs', max_length=100, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='started', help_text='Current transaction status', max_length=20)),
                ('payment_mode', models.CharField(help_text='Payment mode: 1=Card, 10=UPI, 11=Bharat QR', max_length=10)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        # Use RunPython to conditionally remove indexes and constraints
        migrations.RunPython(
            remove_old_indexes_and_constraints,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='account',
            field=models.ForeignKey(help_text='Account being charged', on_delete=django.db.models.deletion.PROTECT, related_name='terminal_transactions', to='emr.account'),
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Optional invoice being paid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_transactions', to='emr.invoice'),
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='payment_reconciliation',
            field=models.OneToOneField(blank=True, help_text='Linked payment reconciliation record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terminal_transaction', to='emr.paymentreconciliation'),
        ),
        migrations.AddField(
            model_name='pinelabstransaction',
            name='terminal',
            field=models.ForeignKey(help_text='Terminal processing this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='care_pinelabs.pinelabsposterminal'),
        ),
        # Use SeparateDatabaseAndState to handle table removal only if it exists
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='pinelabsterminaltransaction',
                    name='account',
                ),
                migrations.RemoveField(
                    model_name='pinelabsterminaltransaction',
                    name='invoice',
                ),
                migrations.RemoveField(
                    model_name='pinelabsterminaltransaction',
                    name='payment_reconciliation',
                ),
                migrations.RemoveField(
                    model_name='pinelabsterminaltransaction',
                    name='terminal',
                ),
            ],
            database_operations=[
                # These will only run if the table exists
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF EXISTS (
                            SELECT FROM information_schema.tables
                            WHERE table_schema = 'public'
                            AND table_name = 'pinelabs_terminal_transaction'
                        ) THEN
                            ALTER TABLE pinelabs_terminal_transaction DROP COLUMN IF EXISTS account_id;
                            ALTER TABLE pinelabs_terminal_transaction DROP COLUMN IF EXISTS invoice_id;
                            ALTER TABLE pinelabs_terminal_transaction DROP COLUMN IF EXISTS payment_reconciliation_id;
                            ALTER TABLE pinelabs_terminal_transaction DROP COLUMN IF EXISTS terminal_id;
                        END IF;
                    END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['terminal', 'status'], name='care_pinela_termina_9cfaaf_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['account', 'status'], name='care_pinela_account_4d4c94_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['invoice', 'status'], name='care_pinela_invoice_998e23_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['status', 'created_date'], name='care_pinela_status_de732e_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['payment_reconciliation'], name='care_pinela_payment_3890ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pinelabstransaction',
            index=models.Index(fields=['plutus_transaction_reference_id'], name='care_pinela_plutus__d374a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'in_progress'])), fields=('terminal',), name='unique_active_transaction_per_terminal', violation_error_message='Terminal already has an active transaction'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), ('status__in', ['started', 'in_progress'])), fields=('invoice',), name='unique_active_payment_per_invoice', violation_error_message='Invoice already has an active payment in progress'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', True), ('status__in', ['started', 'in_progress'])), fields=('account',), name='unique_active_payment_per_account', violation_error_message='Account already has an active payment in progress'),
        ),
        migrations.AddConstraint(
            model_name='pinelabstransaction',
            constraint=models.UniqueConstraint(fields=('transaction_number',), name='unique_transaction_number', violation_error_message='Transaction number already exists'),
        ),
        # Use SeparateDatabaseAndState to only drop table if it exists
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='PinelabsTerminalTransaction',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS pinelabs_terminal_transaction CASCADE;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
