# Generated by Django 6.0 on 2026-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0002_pinelabstransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinelabstransaction',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('failed', 'Failed')], db_index=True, default='started', help_text='Current transaction status', max_length=20),
        ),
    ]