# Generated by Django 6.0 on 2026-07-23 00:00

from django.db import migrations

import care_pinelabs.utils.encrypted_field


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0002_pinelabsconfig_pinelabspositerminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinelabsconfig',
            name='pinelabs_security_token',
            field=care_pinelabs.utils.encrypted_field.EncryptedCharField(),
        ),
    ]
