# Generated by Django 6.0

import django.db.models.deletion
import uuid
from django.db import migrations, models

import care_pinelabs.utils.encrypted_field


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0002_add_terminal_transaction_table'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinelabsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('default_payment_flow', models.CharField(blank=True, choices=[('pinelabs', 'Pinelabs'), ('native', 'Native')], max_length=255, null=True)),
                ('allow_advance_payment', models.BooleanField(default=True)),
                ('allow_partial_payment', models.BooleanField(default=False)),
                ('pinelabs_merchant_id', models.CharField(max_length=255)),
                ('pinelabs_security_token', care_pinelabs.utils.encrypted_field.EncryptedCharField()),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facility.facility')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_pinelabs_pinelabsconfig_created_by', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_pinelabs_pinelabsconfig_updated_by', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinelabsPosTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='care_pinelabs.pinelabsconfig')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emr.device')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_pinelabs_pinelabspositerminal_created_by', to='users.user')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_pinelabs_pinelabspositerminal_updated_by', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PinelabsPaymentMethodMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('care_method', models.CharField(max_length=255)),
                ('pinelabs_method', models.CharField(choices=[('1', 'Card'), ('2', 'Cash'), ('10', 'UPI Sale'), ('11', 'UPI Bharat QR')], max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_mappings', to='care_pinelabs.pinelabsconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='pinelabspaymentmethodmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('config', 'pinelabs_method'), name='unique_care_method_per_config'),
        ),
        migrations.AddConstraint(
            model_name='pinelabspaymentmethodmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False), ('is_default', True)), fields=('config',), name='unique_default_payment_method_per_config'),
        ),
    ]
