# Generated by Django 6.0 on 2026-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0003_alter_pinelabstransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinelabspaymentmethodmapping',
            name='pinelabs_method',
            field=models.CharField(choices=[('1', 'Card'), ('8', 'PhonePe'), ('10', 'UPI Sale'), ('11', 'UPI Bharat QR'), ('21', 'Amazon Pay')], max_length=255),
        ),
        migrations.AlterField(
            model_name='pinelabstransaction',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='started', help_text='Current transaction status', max_length=20),
        ),
    ]
