# Generated by Django 6.0 on 2026-08-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0003_pinelabsconfig_pinelabsposterminal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinelabsterminaltransaction',
            name='new_terminal',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='new_transactions',
                to='care_pinelabs.pinelabsposterminal',
                help_text='Replacement POS terminal, populated by 0005 before the FK swap',
            ),
        ),
    ]
