# Generated by Django 6.0 on 2026-08-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0003_pinelabsconfig_pinelabsposterminal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinelabsterminaltransaction',
            name='terminal',
            field=models.ForeignKey(help_text='Terminal processing this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='care_pinelabs.pinelabsposterminal'),
        ),
        migrations.DeleteModel(
            name='PinelabsTerminal',
        ),
    ]
