# Generated by Django 6.0 on 2026-08-05 14:57

from django.db import migrations


def map_legacy_terminals(apps, schema_editor):
    PinelabsTerminal = apps.get_model('care_pinelabs', 'PinelabsTerminal')
    PinelabsPosTerminal = apps.get_model('care_pinelabs', 'PinelabsPosTerminal')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            'SELECT DISTINCT terminal_id FROM pinelabs_terminal_transaction '
            'WHERE terminal_id IS NOT NULL;'
        )
        legacy_terminal_ids = {row[0] for row in cursor.fetchall()}

    valid_pos_terminals = PinelabsPosTerminal.objects.filter(
        deleted=False, config__deleted=False
    )
    valid_pos_terminal_ids = set(valid_pos_terminals.values_list('id', flat=True))

    def unique_id(queryset):
        ids = list(queryset.values_list('id', flat=True)[:2])
        return ids[0] if len(ids) == 1 else None

    mapping = {}
    for legacy_terminal in PinelabsTerminal.objects.filter(id__in=legacy_terminal_ids):
        same_facility = valid_pos_terminals.filter(
            config__facility_id=legacy_terminal.facility_id
        )
        client_store_match = same_facility.filter(
            device__metadata__client_id=legacy_terminal.client_id,
            device__metadata__store_id=legacy_terminal.store_id,
        )

        pos_terminal_id = unique_id(client_store_match) or (
            same_facility.order_by('id').values_list('id', flat=True).first()
        )
        if pos_terminal_id is not None:
            mapping[legacy_terminal.id] = pos_terminal_id

    errors = [
        legacy_id
        for legacy_id in legacy_terminal_ids
        if mapping.get(legacy_id) not in valid_pos_terminal_ids
    ]
    if errors:
        raise RuntimeError(
            'No active PinelabsPosTerminal exists at the facility for legacy '
            f'PinelabsTerminal ids {sorted(errors)}. Create one before re-running '
            'this migration.'
        )

    with schema_editor.connection.cursor() as cursor:
        for legacy_id, pos_id in mapping.items():
            cursor.execute(
                'UPDATE pinelabs_terminal_transaction SET new_terminal_id = %s '
                'WHERE terminal_id = %s;',
                [pos_id, legacy_id],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0004_add_new_terminal_field'),
    ]

    operations = [
        migrations.RunPython(map_legacy_terminals, migrations.RunPython.noop),
    ]
