# Generated by Django 6.0 on 2026-08-05 14:57

from django.db import migrations


def map_legacy_terminals(apps, schema_editor):
    PinelabsTerminal = apps.get_model('care_pinelabs', 'PinelabsTerminal')
    PinelabsPosTerminal = apps.get_model('care_pinelabs', 'PinelabsPosTerminal')
    PinelabsTerminalTransaction = apps.get_model(
        'care_pinelabs', 'PinelabsTerminalTransaction'
    )

    legacy_terminal_ids = (
        PinelabsTerminalTransaction.objects.values_list('terminal_id', flat=True)
        .distinct()
    )

    unmapped = []
    for legacy_terminal in PinelabsTerminal.objects.filter(
        id__in=legacy_terminal_ids
    ):
        candidates = list(
            PinelabsPosTerminal.objects.filter(
                deleted=False,
                config__facility_id=legacy_terminal.facility_id,
                config__deleted=False,
            )
        )
        if len(candidates) != 1:
            unmapped.append((legacy_terminal.id, legacy_terminal.facility_id, len(candidates)))
            continue

        PinelabsTerminalTransaction.objects.filter(
            terminal_id=legacy_terminal.id
        ).update(new_terminal_id=candidates[0].id)

    if unmapped:
        raise RuntimeError(
            'Cannot unambiguously map the following legacy PinelabsTerminal ids to a '
            'PinelabsPosTerminal (facility_id, candidate_count): '
            f'{unmapped}. Create/identify the correct PinelabsPosTerminal for each '
            'facility and re-run this migration.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0004_add_new_terminal_field'),
    ]

    operations = [
        migrations.RunPython(map_legacy_terminals, migrations.RunPython.noop),
    ]
