# Generated by Django 6.0 on 2026-08-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0005_map_legacy_terminals_to_pos_terminals'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pinelabsterminaltransaction',
            name='pinelabs_te_termina_dff131_idx',
        ),
        migrations.RemoveConstraint(
            model_name='pinelabsterminaltransaction',
            name='unique_active_transaction_per_terminal',
        ),
        migrations.RemoveField(
            model_name='pinelabsterminaltransaction',
            name='terminal',
        ),
        migrations.RenameField(
            model_name='pinelabsterminaltransaction',
            old_name='new_terminal',
            new_name='terminal',
        ),
        migrations.AlterField(
            model_name='pinelabsterminaltransaction',
            name='terminal',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='transactions',
                to='care_pinelabs.pinelabsposterminal',
                db_index=True,
                help_text='Terminal processing this transaction',
            ),
        ),
        migrations.AddIndex(
            model_name='pinelabsterminaltransaction',
            index=models.Index(
                fields=['terminal', 'status'],
                name='pinelabs_te_termina_dff131_idx',
            ),
        ),
        migrations.AddConstraint(
            model_name='pinelabsterminaltransaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    status__in=['started', 'in_progress'],
                ),
                fields=('terminal',),
                name='unique_active_transaction_per_terminal',
                violation_error_message='Terminal already has an active transaction',
            ),
        ),
    ]
