# Generated by Django 6.0 on 2026-08-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_pinelabs', '0006_swap_terminal_fk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinelabsTerminal',
        ),
    ]
